import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import Feed from "../Components/Feed";
import styles from "../styles/Home.module.css";
import { useSession } from "next-auth/react";
import Router from "next/router";
import React, { useEffect } from "react";

export default function Home() {
  const session = useSession();

  useEffect(() => {
    // console.log("home", session);
    if (session.status == "unauthenticated") Router.push("/auth/signin");
  }, [session]);

  return session.status === "loading" ||
    session.status === "unauthenticated" ? (
    ""
  ) : (
    <>
      <div className={"bg-gray-50 h-screen overflow-y-scroll scrollbar-hide"}>
        <Head>
          <title>Instagram</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <Feed />
      </div>
    </>
  );
}
